### PR TITLE
color + latex + favicon + docsgen path

### PR DESCRIPTION
**Pull request by rubenfiszel**

### CODE REVIEW

**Comment by namin** [comment]
@TiarkRompf -- this is pretty cool, Ruben added syntax highlighting to your exported thesis.

**Comment by TiarkRompf** [comment]
Cool, thanks! Two small comments: 

1. In `_layouts/code.html`, some of the indentation seems to be a bit weird (should be easy to fix)
2. Code listings now have a border. Do you like that better? I'm on the fence, but I think I'd prefer to go without.

Thanks again.

**Comment by rubenfiszel** [comment]
Hello.

Sorry to have changed the indentation. My emacs do the whole indentation before saving :/

About borders, I agree but it seems to be the default settings of code-prettify and I wanted to keep the changes minimal.

There is an a bad interaction between code-prettify and MathJax which cause some inline equations to not be rendered inside the <code> tags. The reasons for it is that prettify adds span that make the $ tags out of scope. I'm not sure how to fix.

**Comment by TiarkRompf** [comment]
Just a quick ping -- have you had a chance to look at this again?

**Comment by namin** [comment]
So what would you like Tiark? Should this be reverted?

**Comment by TiarkRompf** [comment]
No reason to revert. I'm all in favor of the change, but it'd be great if the indentation and the borders can be fixed.

**Comment by namin** [comment]
I'll let you two negotiate that, then. Thanks.

**Comment by rubenfiszel** [comment]
I'll take a look this weekend

**Comment by rubenfiszel** [comment]
Fixed in Pull request #9

**Comment by rubenfiszel** [comment]
Edited message above to #10 since I forgot to generate html in #9

**Comment by TiarkRompf** [comment]
Great, thank you! Merged #10.

**Pull request merged**
